labelPRBasedOnFilePath:
  Account:
    - packages/account/**/*
  Components:
    - packages/components/**/*
  Core:
    - packages/core/**/*
  Shared:
    - packages/shared/**/*
  Trader:
    - packages/trader/**/*
  Translations:
    - packages/translations/**/*
  Docs:
    - README.md
    - docs/**/*.md
    - packages/**/*.md
